---
title: "About"
---

# IS415 Project: Point Pattern Analysis

By Group 8: [Teo Jun Peng](https://www.linkedin.com/in/jun-peng-teo/) and [Yu Yiling](https://www.linkedin.com/in/yiling-yu/)

This project is done for IS415 Geospatial Analytics & Application (SMU-X), a module in Singapore Management University (SMU) with the guidance of Professor Kam Tin Seong.

This project is a geospatial analytics project which will create an application to assist users with two kinds of Point Pattern Analysis: Spatial Point Patterns Analysis and Network-Constrained Point Patterns Analysis.

The links you want to check out:

  1. [Project Web page](about.html)
  
  The web page contains everything about our project including our poster, user guide and research paper.
  
  2. [Project R Shiny application](https://yiling-yu.shinyapps.io/is415_project_shiny_app/)
  
  The R Shiny application allows users to perform two methods of Point Pattern Analysis: SPPA and NetSPPA. 
  Check our user guide [here](https://github.com/yiling-yu/IS415_Project/blob/master/User%20Guide.pdf)~




  
  